services:
  php:
    container_name: payment-php
    entrypoint: php bin/hyperf.php server:watch
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    container_name: payment-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperf
      MYSQL_USER: hyperf
      MYSQL_PASSWORD: hyperf
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: payment
