services:
  php:
    container_name: payment-php
    entrypoint: php bin/hyperf.php server:watch
    build:
      context: .
      args:
        - XDEBUG=true
    volumes:
      - ./:/opt/www
      - ./xdebug.ini:/etc/php82/conf.d/50_xdebug.ini
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
      - XDEBUG_MODE=debug,develop
      - XDEBUG_CONFIG=client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    container_name: payment-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: payment
