openapi: 3.1.0
info:
  title: Payment API
  description: API para realizar pagamentos
  version: 1.0.0

servers:
  - url: http://localhost:9501

paths:
  /auth/sign-up:
    post:
      summary: Registra um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        422:
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    example: "Erro de validação"

  /auth/sign-in:
    post:
      summary: Logue em sua conta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        200:
          description: Logado com sucesso, Token gerado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: O token JWT de autenticação
        401:
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    example: "Credenciais inválidas"

  /transactions/transfer:
    post:
      summary: Realiza uma transferência
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        200:
          description: Transfer successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResource'
        403:
          description: Saldo insuficiente / Usuário Lojista (shopkeeper)
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    example: "Saldo insuficiente"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SignUpRequest:
      type: object
      properties:
        type:
          type: string
          enum: [ common, shopkeeper ]
          default: common
          description: O tipo do usuário lojista/comum
        firstName:
          required: true
          type: string
          description: O primeiro nome do usuário
        lastName:
          required: true
          type: string
          description: O sobrenome do usuário
        email:
          required: true
          type: string
          description: O email do usuário
        document:
          required: true
          type: string
          description: O CPF/CPNJ do usuário
        password:
          required: true
          type: string
          description: A senha do usuário
        passwordConfirmation:
          required: true
          type: string
          description: A confirmação da senha

    SignInRequest:
      type: object
      properties:
        email:
          required: true
          type: string
          description: O email do usuário
        password:
          required: true
          type: string
          description: A senha do usuário

    TransferRequest:
      type: object
      properties:
        value:
          required: true
          type: number
          description: A quantia a ser transferida
        payer:
          required: true
          type: number
          description: O Id do usuário que irá pagar
        payee:
          required: true
          type: number
          description: O Id do usuário que irá receber

    UserResource:
      type: object
      properties:
        id:
          type: number
          description: O Id do usuário
        type:
          type: string
          enum: [ common, shopkeeper ]
          description: O tipo do usuário lojista/comum
        firstName:
          type: string
          description: O primeiro nome do usuário
        lastName:
          type: string
          description: O sobrenome do usuário
        email:
          type: string
          format: email
          description: O email do usuário
        wallet:
          $ref: '#/components/schemas/WalletResource'

    WalletResource:
      type: object
      properties:
        balance:
          type: number
          description: O saldo da carteira

    TransactionResource:
      type: object
      properties:
        amount:
          type: number
          description: A quantia da transação
        payerUserId:
          type: number
          description: O Id do usuário que pagou
        payeeUserId:
          type: number
          description: O Id do usuário que recebeu
